"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
type Preview={posts:number;missingFields:string[];examples:{id:string;text:string}[];warning:string};
export default function MetricsImport({platform}:{platform:string}) {
  const router=useRouter();const[csv,setCsv]=useState("");const[time,setTime]=useState("");const[preview,setPreview]=useState<Preview|null>(null);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
  async function submit(confirm:boolean) {
    setBusy(true);setNotice("");
    try {const response=await fetch(`/api/metrics/import/${platform}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({csv,capturedAt:time?new Date(time).toISOString():null,confirm})});const data=await response.json();if(!response.ok){setNotice(data.error||"Import failed.");return;}if(confirm){setPreview(null);setNotice("Imported measurements saved. Their source is labelled CSV.");router.refresh();}else setPreview(data);}
    catch{setNotice("Could not validate or import this file. Check your connection and measurement date.");}finally{setBusy(false);}
  }
  return <details className="rounded-xl border border-border bg-surface p-4"><summary className="cursor-pointer text-sm font-medium text-ink">Import measurements from CSV</summary><div className="mt-4 space-y-3"><p className="text-xs text-ink-muted">No platform API calls. Free: up to 10 posts; Pro: up to 100. Blank counts stay unknown. Rename your export headers to match the template.</p><a className="text-sm text-navy underline" href={`/metrics-${platform}-template.csv`} download>Download CSV template</a><label className="block text-sm">CSV file<input className="mt-1 block w-full text-sm" type="file" accept=".csv,text/csv" disabled={busy} onChange={async e=>{setPreview(null);setNotice("");const file=e.target.files?.[0];if(!file){setCsv("");return;}if(file.size>524288){setCsv("");setNotice("Use a file smaller than 512 KB.");return;}setCsv(await file.text());}}/></label><label className="block text-sm">When were these counts measured?<input type="datetime-local" value={time} disabled={busy} onChange={e=>{setTime(e.target.value);setPreview(null);}} className="mt-1 block rounded border border-border p-2 text-sm"/></label><button disabled={busy||!csv||!time} onClick={()=>submit(false)} className="rounded bg-navy px-3 py-2 text-sm text-white disabled:opacity-50">{busy?"Checking...":"Preview import"}</button>{preview&&<div className="rounded border border-border p-3 text-sm"><p>{preview.posts} posts. Missing fields: {preview.missingFields.join(", ")||"None"}.</p><p className="mt-2 text-xs text-ink-muted">{preview.warning}</p>{preview.examples.map(p=><p className="mt-2" key={p.id}>{p.id}: {p.text}</p>)}<button disabled={busy} onClick={()=>submit(true)} className="mt-3 rounded bg-navy px-3 py-2 text-white disabled:opacity-50">Confirm import</button></div>}{notice&&<p role="status" className="text-sm text-ink">{notice}</p>}</div></details>;
}
