"use client";
import dynamic from "next/dynamic";
import type { VideoRetention } from "@/lib/youtube-retention";
const YouTubeRetention=dynamic(()=>import("./YouTubeRetention"));
import { useState } from "react";
import type { YouTubeReport } from "@/lib/youtube-reports";
import type { CollectedPost } from "@/lib/metric-measurements";

type Data = { profile:{name:string;followers:number|null;totalPosts:number|null}; posts:CollectedPost[]; measuredAt:string; analytics:{period:{startDate:string;endDate:string;timeZone:string};reports:Record<string,YouTubeReport>;warnings:string[];retention:VideoRetention[]}|null };
const METRICS:Record<string,string>={views:"Views",engagedViews:"Engaged views",estimatedMinutesWatched:"Watch time (minutes)",averageViewDuration:"Average view duration (seconds)",averageViewPercentage:"Average percentage viewed (%)",likes:"Likes",comments:"Comments",shares:"Shares",subscribersGained:"Subscribers gained",subscribersLost:"Subscribers lost"};
const DIMENSIONS:Record<string,string>={day:"Date",insightTrafficSourceType:"Traffic source",country:"Country",subscribedStatus:"Viewer subscription",creatorContentType:"Content type"};
const SECTIONS:Record<string,string>={daily:"Daily viewing",traffic:"Traffic sources",countries:"Viewer countries",viewers:"Subscribed and unsubscribed viewers",formats:"Content formats"};
function display(value:string|number|null|undefined){return value==null?"Unavailable":typeof value==="number"?value.toLocaleString("en-US",{maximumFractionDigits:2}):value;}
export default function YouTubeMetrics(){
  const [days,setDays]=useState<7|28|90>(28);const [loading,setLoading]=useState(false);const [data,setData]=useState<Data|null>(null);const [message,setMessage]=useState("");const [error,setError]=useState("");
  async function refresh(){setLoading(true);setError("");setMessage("");try{const response=await fetch("/api/metrics/refresh/youtube",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({days,postLimit:10}),cache:"no-store"});const result=await response.json();if(!response.ok){setError(typeof result.error==="string"?result.error:"YouTube collection failed.");return;}if(result.youtube)setData(result.youtube);setMessage(result.cached?`Signal limits how often reports can be loaded. ${result.nextAllowedAt?`Try after ${new Date(result.nextAllowedAt).toLocaleString("en-US",{timeZone:"UTC"})} UTC.`:"Try again later."}`:result.warning??"");}catch{setError("Could not reach Signal. Try again later.");}finally{setLoading(false);}}
  const overview=data?.analytics?.reports.overview;
  return <div className="space-y-5">
    <div className="surface-card p-6">
      <h1 className="font-display text-2xl font-semibold text-ink">YouTube analytics</h1>
      <p className="mt-2 text-sm leading-6 text-ink-muted">Official reports for your connected channel. Watch time, viewing duration and audience breakdowns keep YouTube’s own definitions.</p>
      <div className="mt-4 flex flex-wrap items-end gap-3"><label className="text-sm text-ink-muted">Reporting window<select aria-label="Reporting window" className="ml-3 rounded-lg border border-border bg-surface p-2 text-ink" value={days} onChange={event=>setDays(Number(event.target.value) as 7|28|90)} disabled={loading}><option value={7}>7 days</option><option value={28}>28 days</option><option value={90}>90 days</option></select></label><button type="button" className="rounded-xl bg-navy px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" disabled={loading} onClick={refresh}>{loading?"Loading reports…":"Load reports"}</button><a href="https://studio.youtube.com/" target="_blank" rel="noopener noreferrer" className="text-sm text-navy underline">Open YouTube Studio</a></div>
      <p className="mt-3 text-xs leading-5 text-ink-muted">Reports end three reporting days before today to allow processing. YouTube may still return fewer days or withhold small audience breakdowns. Loaded data stays only for this visit. Signal applies its own refresh and daily limits.</p>
      {error&&<p role="alert" className="mt-3 text-sm text-red-600">{error}</p>}{message&&<p role="status" className="mt-3 text-sm text-ink-muted">{message}</p>}
    </div>
    {data&&<>
      <div className="surface-card p-6"><h2 className="font-display text-lg font-semibold text-ink">{data.profile.name}</h2><p className="mt-1 text-xs text-ink-muted">Measured {new Date(data.measuredAt).toLocaleString("en-US",{timeZone:"UTC"})} UTC</p><dl className="mt-4 grid grid-cols-2 gap-4"><div><dt className="text-xs text-ink-muted">Subscribers (may be rounded or hidden)</dt><dd className="mt-1 text-xl text-ink">{display(data.profile.followers)}</dd></div><div><dt className="text-xs text-ink-muted">Public videos</dt><dd className="mt-1 text-xl text-ink">{display(data.profile.totalPosts)}</dd></div></dl></div>
      {data.analytics&&<div className="surface-card p-6"><h2 className="font-display text-lg font-semibold text-ink">Channel report</h2><p className="mt-1 text-xs text-ink-muted">Requested {data.analytics.period.startDate} through {data.analytics.period.endDate}, inclusive. Reporting days: America/Los_Angeles.</p><dl className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3">{Object.entries(METRICS).map(([key,label])=><div key={key}><dt className="text-xs text-ink-muted">{label}</dt><dd className="mt-1 text-xl text-ink">{display(overview?.rows[0]?.[overview.columns.indexOf(key)])}</dd></div>)}</dl><p className="mt-4 text-xs leading-5 text-ink-muted">These are date-range metrics, separate from video lifetime counters. Watch time adds viewing minutes across the channel. Average duration measures viewing seconds per view; average percentage viewed measures the portion watched on average. It is not a retention curve. Revenue requires separate consent and an eligible monetized channel. Signal Score and AI comparisons do not use YouTube data.</p></div>}
      {data.analytics&&Object.entries(SECTIONS).map(([key,title])=>{const report=data.analytics!.reports[key];return <section key={key} className="surface-card p-6"><h2 className="font-display text-lg font-semibold text-ink">{title}</h2>{report?.rows.length?<div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><caption className="sr-only">{title} for the requested YouTube reporting period</caption><thead><tr>{report.columns.map(column=><th key={column} scope="col" className="border-b border-border px-2 py-2 font-semibold text-ink-muted">{METRICS[column]??DIMENSIONS[column]??column}</th>)}</tr></thead><tbody>{report.rows.map((row,index)=><tr key={index}>{row.map((value,i)=><td key={i} className="border-b border-border px-2 py-2 text-ink">{display(value)}</td>)}</tr>)}</tbody></table></div>:<p className="mt-2 text-sm text-ink-muted">No report rows available. This does not mean zero activity.</p>}</section>;})}
      {data.analytics?.retention?.length ? <YouTubeRetention videos={data.analytics.retention} /> : null}
      <section className="surface-card p-6"><h2 className="font-display text-lg font-semibold text-ink">Recent public videos</h2><p className="mt-1 text-xs text-ink-muted">Lifetime counters at measurement time. No custom engagement scores.</p><div className="mt-4 space-y-4">{data.posts.length?data.posts.map(post=><div key={post.id} className="border-t border-border pt-3"><a href={post.url??"https://www.youtube.com/"} target="_blank" rel="noopener noreferrer" className="text-sm font-semibold text-navy underline">{post.text}</a><p className="mt-1 text-xs text-ink-muted">Views: {display(post.viewCount)} · Likes: {display(post.likeCount)} · Comments: {display(post.replyCount)}</p></div>):<p className="text-sm text-ink-muted">No public videos returned.</p>}</div></section>
    </>}
  </div>;
}
