import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { mkdtempSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomBytes } from "node:crypto";
import { spawn } from "node:child_process";
import { once } from "node:events";
import { createServer } from "node:net";
import bcrypt from "bcryptjs";
const folder=mkdtempSync(join(tmpdir(),"signal-scheduling-http-"));
Object.assign(process.env,{DATABASE_PROVIDER:"sqlite",DATABASE_URL:"file:"+join(folder,"test.db"),AUTH_SECRET:randomBytes(32).toString("hex"),EMAIL_PROVIDER:"disabled",SIGNAL_SCHEDULING_ENABLED:"true",SIGNAL_SCHEDULER_CONFIGURED:"true",CRON_SECRET:randomBytes(32).toString("hex"),X_CLIENT_ID:"fixture-client",X_CLIENT_SECRET:"fixture-secret"});
delete process.env.VERCEL;
const require=createRequire(import.meta.url);const Database=require("better-sqlite3");const db=new Database(join(folder,"test.db"));
const migrations=new URL("../prisma/migrations/",import.meta.url);
for(const m of readdirSync(migrations).sort())if(m!=="migration_lock.toml")db.exec(readFileSync(new URL(m+"/migration.sql",migrations),"utf8"));
db.close();
const {prisma}=await import("../lib/prisma.ts");
const allocator=createServer();allocator.listen(0,"127.0.0.1");await once(allocator,"listening");const address=allocator.address();assert.ok(address&&typeof address!=="string");const port=address.port;await new Promise<void>(r=>allocator.close(()=>r()));
const base=`http://127.0.0.1:${port}`;process.env.APP_URL=base;
const server=spawn(process.execPath,["node_modules/next/dist/bin/next","start","-H","127.0.0.1","-p",String(port)],{env:{...process.env,NODE_ENV:"production",AUTH_TRUST_HOST:"true",AUTH_URL:base,NEXTAUTH_URL:base,NEXT_TELEMETRY_DISABLED:"1"},stdio:["ignore","pipe","pipe"]});
server.stderr.resume();
try{
 await new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error("Startup timeout")),20000);server.stdout.on("data",b=>{if(b.toString().includes("Ready")){clearTimeout(timeout);resolve();}});server.on("exit",()=>{clearTimeout(timeout);reject(new Error("Server stopped"));});});
 const email="queue-test@example.com",password="test-only-signal-password";
 const user=await prisma.user.create({data:{email,hashedPassword:await bcrypt.hash(password,10)}});
 const account=await prisma.connectedAccount.create({data:{userId:user.id,platform:"x",platformUserId:"123",accessToken:"NEVER_SERIALIZE_THIS_TOKEN"}});
 const jar=new Map<string,string>();
 function accept(response:Response){for(const value of response.headers.getSetCookie()){const part=value.split(";")[0],split=part.indexOf("=");jar.set(part.slice(0,split),part.slice(split+1));}}
 const cookies=()=>[...jar].map(([k,v])=>`${k}=${v}`).join("; ");
 const csrf=await fetch(base+"/api/auth/csrf");accept(csrf);const {csrfToken}=await csrf.json();
 accept(await fetch(base+"/api/auth/callback/credentials",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",Cookie:cookies(),Origin:base,"X-Auth-Return-Redirect":"1"},body:new URLSearchParams({email,password,csrfToken,callbackUrl:base+"/dashboard"}),redirect:"manual"}));
 assert.equal((await (await fetch(base+"/api/auth/session",{headers:{Cookie:cookies()}})).json()).user.id,user.id);
 const request=(path:string,body:object,method="POST",origin=base,cookie=cookies())=>fetch(base+path,{method,headers:{"Content-Type":"application/json",Origin:origin,Cookie:cookie},body:JSON.stringify(body)});
 const saved=await request("/api/drafts",{text:"Scheduled fixture",targetIds:[account.id],mediaUrl:"",scheduledFor:null});assert.equal(saved.status,201);let draft=await saved.json();
 const schedule=`/api/drafts/${draft.id}/schedule`,when=new Date(Date.now()+5*60000).toISOString();
 const payload={action:"schedule",confirm:true,expectedUpdatedAt:draft.updatedAt,scheduledFor:when};
 assert.equal((await request(schedule,payload,"POST",base,"")).status,401);
 assert.equal((await request(schedule,payload,"POST","https://untrusted.example")).status,403);
 assert.equal((await request(schedule,{...payload,confirm:false})).status,400);
 assert.equal((await request(schedule,payload)).status,200);
 assert.equal((await request(schedule,payload)).status,409);
 draft=await prisma.contentDraft.findUniqueOrThrow({where:{id:draft.id}});
 assert.equal((await request(`/api/drafts/${draft.id}`,{text:"changed",targetIds:[account.id],expectedUpdatedAt:draft.updatedAt.toISOString()},"PATCH")).status,409);
 assert.equal((await fetch(base+`/api/drafts/${draft.id}`,{method:"DELETE",headers:{Origin:base,Cookie:cookies()}})).status,409);
 assert.equal((await fetch(base+"/api/cron/publishing")).status,401);
 const tick=await fetch(base+"/api/cron/publishing",{headers:{Authorization:`Bearer ${process.env.CRON_SECRET}`}});assert.equal(tick.status,200);assert.equal((await tick.json()).processed,0);
 const page=await fetch(base+"/dashboard/queue",{headers:{Cookie:cookies()}});assert.equal(page.status,200);const html=await page.text();assert.match(html,/Publishing queue/);assert.match(html,/Scheduled fixture/);assert.doesNotMatch(html,/NEVER_SERIALIZE_THIS_TOKEN/);
 assert.equal((await request(schedule,{action:"cancel",confirm:true,expectedUpdatedAt:draft.updatedAt.toISOString()})).status,200);
 assert.equal((await prisma.contentDraft.findUniqueOrThrow({where:{id:draft.id}})).status,"DRAFT");
 console.log("Scheduling HTTP smoke passed: login, confirmation, CSRF, stale revisions, queued editing/deletion locks, cron authorization, queue render, token isolation and cancellation. No provider calls.");
}finally{server.kill("SIGTERM");if(server.exitCode===null)await once(server,"exit");await prisma.$disconnect();rmSync(folder,{recursive:true,force:true});}
